image: Visual Studio 2017
init:
  - ps: |
      if ($Env:APPVEYOR_REPO_TAG -eq "true") { Update-AppveyorBuild -Version "$Env:APPVEYOR_REPO_TAG_NAME" }
      else { Update-AppveyorBuild -Version "dev-$($Env:APPVEYOR_REPO_COMMIT.Substring(0, 7))" }
configuration: Release
build:
  parallel: true
after_build:
  - ps: |
      $project = $Env:APPVEYOR_PROJECT_NAME
      $name = "$project-$Env:APPVEYOR_BUILD_VERSION"
      $dir = "$project\bin\$Env:CONFIGURATION"
      md "$name"
      cp @("$dir\$project.exe", "$dir\$project.exe.config", "LICENSE") "$name"
      7z a "$name.zip" "$name"
artifacts:
  - path: '*.zip'
deploy:
  - provider: GitHub
    artifact: /.*\.zip/
    description: |
      **Release Notes**
      - Many new features.
      - Use the API from wslapi.dll to perform most of the operation, so this program no longer depends on LxRun.exe.
    auth_token:
      secure: saJApLHQjPJ+XmMy3Qk+khAvfIKI4dveBtSnUESRX14qpUy3WPlhM97Ixbja/Tjg
    on:
      appveyor_repo_tag: true
